import json

def transform(data):
    f = open("public/tutor_data.json", "w")
    f.write("[\n")
    for i in range(len(data)):
        student = data[i]
        student["mathcore"] = None if student["mathcore"] == "None" else student["mathcore"].split(", ")
        student["moreMath"] = None if student["moreMath"] == "None" else student["moreMath"].split(", ")
        student["cs"] = None if student["cs"] == "None" else student["cs"].split(", ")
        student["biology"] = None if student["biology"] == "None" else student["biology"].split(", ")
        student["chemistry"] = None if student["chemistry"] == "None" else student["chemistry"].split(", ")
        student["physics"] = None if student["physics"] == "None" else student["physics"].split(", ")
        student["language"] = None if student["language"] == "None" else student["language"].split(", ")
        student["otherScience"] = None if student["otherScience"] == "None" else student["otherScience"].split(", ")
        student["aboutMe"] = student.pop("aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences")
        del student["timestamp"]
        f.write(json.dumps(student))
        f.write("," if i != len(data) - 1 else "")
        f.write("\n")
    f.write("]")


d = [
    {
        "timestamp": "2023-10-02T23:45:17.598Z",
        "emailAddress": "vyou@imsa.edu",
        "firstName": "Vincent",
        "lastName": "You",
        "hall": 1505,
        "wing": "B",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "Hi! My name's Vincent and I'm excited to help you with your courses. When I'm not studying for my next math test, I enjoy playing the saxophone and programming.",
        "mathcore": "MI IV, BC I",
        "moreMath": "None",
        "cs": "CSI",
        "biology": "None",
        "chemistry": "SI Chemistry",
        "physics": "SI Physics",
        "language": "German I",
        "otherScience": "MSI",
        "id": 125236,
        "graduationYear": 2025
    },
    {
        "timestamp": "2023-10-04T04:14:27.677Z",
        "emailAddress": "zcai@imsa.edu",
        "firstName": "Zhuoer",
        "lastName": "Cai",
        "hall": 1501,
        "wing": "D",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "Hi I'm Zhuoer. I can tutor MI II and MI III, I'm in MI IV, BC I, and intro to proofs this semester",
        "mathcore": "MI II, MI III",
        "moreMath": "None",
        "cs": "None",
        "biology": "None",
        "chemistry": "None",
        "physics": "None",
        "language": "None",
        "otherScience": "None",
        "id": 125027,
        "graduationYear": 2025
    },
    {
        "timestamp": "2023-10-04T04:59:45.807Z",
        "emailAddress": "abrahmandam@imsa.edu",
        "firstName": "Arjun",
        "lastName": "Brahmandam ",
        "hall": 1505,
        "wing": "C",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "Hey guys! I’m a huge math, music, and ping pong nerd and will talk to anyone about anything (even something I don’t know of). I’m ambi/omniverted as well and have a hobby of listening to random convos besides me without being in the mood to engage in them, so I completely understand both sides of the spectrum. So feel free to ask me anything about that part as well, no matter who you are. ",
        "mathcore": "MI I/II, MI II, MI III, MI IV, BC I",
        "moreMath": "Statistics",
        "cs": "CSI",
        "biology": "None",
        "chemistry": "SI Chemistry",
        "physics": "None",
        "language": "Spanish II, Spanish III",
        "otherScience": "None",
        "anyOtherCoursesNotListedAbove": "I can also tutor music theory if needed. ",
        "id": 125022,
        "graduationYear": 2025
    },
    {
        "timestamp": "2023-10-04T05:15:29.358Z",
        "emailAddress": "dleigh@imsa.edu",
        "firstName": "Dashiell",
        "lastName": "Leigh",
        "hall": 1501,
        "wing": "B",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "Hi I'm Dash (he/him). I'm a math nerd, I'm involved in Diversity, Equity, and Inclusion at IMSA, and I like taking long walks on the beach and looking pretentiously up at the stars while I listen to Radiohead. In all seriousness, I love music and dancing and just talking to people, and I'm always here to chat.",
        "mathcore": "Geometry, MI I/II, MI II, MI III, MI IV, BC I, BC II, BC III",
        "moreMath": "Differential Equations",
        "cs": "None",
        "biology": "None",
        "chemistry": "None",
        "physics": "None",
        "language": "Spanish II, Spanish III, Spanish IV, Spanish V",
        "otherScience": "Biophysics",
        "id": 124115,
        "graduationYear": 2024
    },
    {
        "timestamp": "2023-10-04T13:03:34.053Z",
        "emailAddress": "pcahill@imsa.edu",
        "firstName": "Patrick ",
        "lastName": "Cahill",
        "hall": 1505,
        "wing": "D",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "I'm happy to talk about anything, and you can contact me anytime ",
        "mathcore": "Geometry, MI II, MI III",
        "moreMath": "None",
        "cs": "CSI",
        "biology": "None",
        "chemistry": "SI Chemistry",
        "physics": "SI Physics",
        "language": "German I",
        "otherScience": "MSI",
        "anyOtherCoursesNotListedAbove": "Nope ",
        "id": 125025,
        "graduationYear": 2025
    },
    {
        "timestamp": "2023-10-04T15:42:31.460Z",
        "emailAddress": "smehendale@imsa.edu",
        "firstName": "Shridhar",
        "lastName": "Mehendale",
        "hall": 1505,
        "wing": "A",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "Junior with a passion in math and business. ",
        "mathcore": "MI I/II, MI II, MI III, MI IV, BC I",
        "moreMath": "None",
        "cs": "CSI",
        "biology": "None",
        "chemistry": "SI Chemistry",
        "physics": "SI Physics",
        "language": "None",
        "otherScience": "None",
        "id": 125136,
        "graduationYear": 2025
    },
    {
        "timestamp": "2023-10-04T19:53:47.236Z",
        "emailAddress": "wguo@imsa.edu",
        "firstName": "William",
        "lastName": "Guo",
        "hall": 1505,
        "wing": "B",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "Junior in 05 B Wing. Enjoys golf and sports.",
        "mathcore": "MI III, MI IV, BC I",
        "moreMath": "None",
        "cs": "CSI",
        "biology": "None",
        "chemistry": "SI Chemistry",
        "physics": "SI Physics",
        "language": "French I",
        "otherScience": "MSI",
        "id": 125072,
        "graduationYear": 2025
    },
    {
        "timestamp": "2023-10-05T03:36:18.144Z",
        "emailAddress": "lbrower@imsa.edu",
        "firstName": "Lucas",
        "lastName": "Brower",
        "hall": 1505,
        "wing": "B",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "In my free time I like to play basketball, workout, and finish my CompuSci assignments.",
        "mathcore": "MI II, MI III, MI IV, BC I, BC II",
        "moreMath": "None",
        "cs": "CSI, OOP",
        "biology": "Advanced Biological Systems",
        "chemistry": "SI Chemistry",
        "physics": "SI Physics",
        "language": "None",
        "otherScience": "None",
        "id": 124025,
        "graduationYear": 2024
    },
    {
        "timestamp": "2023-10-07T01:24:03.808Z",
        "emailAddress": "yyardi@imsa.edu",
        "firstName": "Yash",
        "lastName": "Yardi",
        "hall": 1505,
        "wing": "B",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "I enjoy working in computer science and math. In my free time I like to play sports and be outside, and when I am working I prefer the indoors where there are far less distractions and I can stay focused. ",
        "mathcore": "MI III, MI IV, BC I",
        "moreMath": "None",
        "cs": "CSI, OOP",
        "biology": "None",
        "chemistry": "None",
        "physics": "SI Physics",
        "language": "Spanish II",
        "otherScience": "MSI",
        "id": 125298,
        "graduationYear": 2025
    },
    {
        "timestamp": "2023-10-16T02:11:30.983Z",
        "emailAddress": "mchen2@imsa.edu",
        "firstName": "Max",
        "lastName": "Chen",
        "hall": 1501,
        "wing": "D",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "Hi, I'm Max!",
        "mathcore": "None",
        "moreMath": "None",
        "cs": "None",
        "biology": "None",
        "chemistry": "None",
        "physics": "SI Physics",
        "language": "None",
        "otherScience": "None",
        "id": 125033,
        "graduationYear": 2025
    },
    {
        "timestamp": "2023-10-16T04:07:28.605Z",
        "emailAddress": "pveeramachaneni@imsa.edu",
        "firstName": "Prabhav",
        "lastName": "Veeramachaneni",
        "hall": 1501,
        "wing": "D",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "Hi I'm Prabhav. I live in 1501 D wing and am a Junior. I enjoy video editing and am always eager to learn more. If you ever need help feel free to ask, I'll try my best.",
        "mathcore": "MI III, MI IV, BC I",
        "moreMath": "None",
        "cs": "CSI",
        "biology": "None",
        "chemistry": "SI Chemistry",
        "physics": "SI Physics",
        "language": "Spanish II",
        "otherScience": "MSI",
        "id": 125294,
        "graduationYear": 2025
    },
    {
        "timestamp": "2023-10-16T13:58:10.072Z",
        "emailAddress": "lbannon@imsa.edu",
        "firstName": "Sori",
        "lastName": "Bannon",
        "hall": 1501,
        "wing": "B",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "IMSAs most obnoxious queer, unless you think you could do better. I tutor in CSI, WebTech, and OOP. You can find me in the hall commons 7:30-9 on Mondays, Tuesdays, and Thursdays.",
        "mathcore": "None",
        "moreMath": "None",
        "cs": "CSI, OOP, Web Technologies",
        "biology": "None",
        "chemistry": "None",
        "physics": "None",
        "language": "None",
        "otherScience": "None",
        "anyOtherCoursesNotListedAbove": "Speculative Fiction",
        "id": 124016,
        "graduationYear": 2024
    },
    {
        "timestamp": "2023-10-16T14:39:22.890Z",
        "emailAddress": "dxianto@imsa.edu",
        "firstName": "Dylan",
        "lastName": "Xianto",
        "hall": 1501,
        "wing": "D",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "I am Dylan, a tutor for 1501. I am very fond of science, especially chemistry.",
        "mathcore": "Geometry, MI I/II, MI II, MI III, MI IV, BC I, BC II",
        "moreMath": "None",
        "cs": "OOP",
        "biology": "None",
        "chemistry": "SI Chemistry, Advanced Chemistry, Environmental Chemistry",
        "physics": "SI Physics",
        "language": "None",
        "otherScience": "MSI",
        "id": 125230,
        "graduationYear": 2025
    },
    {
        "timestamp": "2023-10-16T15:01:58.634Z",
        "emailAddress": "rmandell@imsa.edu",
        "firstName": "Bobby",
        "lastName": "Mandell",
        "hall": 1505,
        "wing": "A",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "Hi my name is Bobby. I love hockey, and I play left wing. I have great friends and an awesome quad. Feel free to come to me with any questions or if you just want to chat!",
        "mathcore": "Geometry, MI I/II, MI II, MI III, MI IV, BC I",
        "moreMath": "None",
        "cs": "CSI, OOP",
        "biology": "Advanced Biological Systems",
        "chemistry": "None, SI Chemistry",
        "physics": "SI Physics, Modern Physics",
        "language": "Spanish II, Spanish III",
        "otherScience": "MSI",
        "id": 125130,
        "graduationYear": 2025
    },
    {
        "timestamp": "2023-10-16T19:24:47.172Z",
        "emailAddress": "blamb1@imsa.edu",
        "firstName": "Bryan",
        "lastName": "Lamb",
        "hall": 1505,
        "wing": "D",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "My name is Bryan, I'm a junior, and I really like being a peer tutor. I don't have one subject that I am the greatest at tutoring, but my favorite in general and to help with is physics. I look forward to helping where I can. ",
        "mathcore": "MI III, MI IV, BC I, BC II, BC III",
        "moreMath": "None",
        "cs": "None",
        "biology": "None",
        "chemistry": "SI Chemistry",
        "physics": "SI Physics",
        "language": "German I, German II",
        "otherScience": "None",
        "id": 125114,
        "graduationYear": 2025
    },
    {
        "timestamp": "2023-10-17T00:25:16.754Z",
        "emailAddress": "ekemph@imsa.edu",
        "firstName": "Evan",
        "lastName": "Kemph",
        "hall": 1505,
        "wing": "D",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "I am friendly, I don't bite! I like computers, engineering, and math. I am happy to help with any problem that I can.",
        "mathcore": "MI I/II, MI II, MI III",
        "moreMath": "None",
        "cs": "CSI",
        "biology": "None",
        "chemistry": "SI Chemistry",
        "physics": "SI Physics",
        "language": "Mandarin I",
        "otherScience": "MSI",
        "id": 125102,
        "graduationYear": 2025
    },
    {
        "timestamp": "2023-10-17T22:31:10.403Z",
        "emailAddress": "dcano@imsa.edu",
        "firstName": "Daniel",
        "lastName": "Cano",
        "hall": 1501,
        "wing": "D",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "Hi, my name is Dani. I love anime, videogames, cooking, and just about everything science. ",
        "mathcore": "MI I/II, MI II, MI III, MI IV",
        "moreMath": "None",
        "cs": "None",
        "biology": "Advanced Biological Systems",
        "chemistry": "SI Chemistry, Advanced Chemistry",
        "physics": "None",
        "language": "Mandarin I, Mandarin II",
        "otherScience": "None",
        "id": 124029,
        "graduationYear": 2024
    },
    {
        "timestamp": "2023-10-21T02:50:47.416Z",
        "emailAddress": "xalbertson@imsa.edu",
        "firstName": "Xander",
        "lastName": "Albertson",
        "hall": 1505,
        "wing": "D",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "My name is Xander and I love to hang out with my friends and play all different media of games. Some of my favorites are Magic the Gathering, Marvel Villainous, and Super Smash Bros. If you’re looking for me you can probably find me in the gym because I also love to work out. My favorite food is barbecue chicken drumstick. I also have a crippling addiction to sleep.",
        "mathcore": "MI III, MI IV",
        "moreMath": "None",
        "cs": "OOP",
        "biology": "None",
        "chemistry": "SI Chemistry",
        "physics": "None",
        "language": "None",
        "otherScience": "None",
        "id": 125006,
        "graduationYear": 2025
    },
    {
        "timestamp": "2023-10-21T03:20:46.979Z",
        "emailAddress": "ichung@imsa.edu",
        "firstName": "Ian",
        "lastName": "Chung",
        "hall": 1501,
        "wing": "D",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "I am a peer tutor",
        "mathcore": "MI I/II, MI II, MI III, MI IV, BC I",
        "moreMath": "None",
        "cs": "None",
        "biology": "None",
        "chemistry": "SI Chemistry",
        "physics": "None",
        "language": "French I",
        "otherScience": "MSI",
        "id": 125038,
        "graduationYear": 2025
    },
    {
        "timestamp": "2023-10-21T03:58:06.867Z",
        "emailAddress": "shattarki@imsa.edu",
        "firstName": "Shrishant",
        "lastName": "Hattarki",
        "hall": 1505,
        "wing": "C",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "Hi, I’m Shrishant, and I’m a junior in 05 C wing. I tutor anything math/cs related on Tuesdays, Wednesdays , and Thursdays.",
        "mathcore": "MI IV, BC I",
        "moreMath": "None",
        "cs": "CSI, OOP",
        "biology": "None",
        "chemistry": "None",
        "physics": "None",
        "language": "None",
        "otherScience": "None",
        "id": 125080,
        "graduationYear": 2025
    },
    {
        "timestamp": "2023-10-22T21:48:21.850Z",
        "emailAddress": "ashah1@imsa.edu",
        "firstName": "Aaditya",
        "lastName": "Shah",
        "hall": 1505,
        "wing": "A",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "Hi, my name is Aadi Shah, and I'm a junior and a peer tutor for 05. I like to spend my free time hanging out with friends, listening to music, and watching/playing sports.",
        "mathcore": "MI III, MI IV, BC I",
        "moreMath": "None",
        "cs": "CSI, OOP, Web Technologies",
        "biology": "None",
        "chemistry": "SI Chemistry",
        "physics": "SI Physics",
        "language": "Spanish II, Spanish III",
        "otherScience": "MSI, Engineering",
        "id": 125188,
        "graduationYear": 2025
    },
    {
        "timestamp": "2023-10-23T01:04:34.717Z",
        "emailAddress": "njoseph1@imsa.edu",
        "firstName": "Noel",
        "lastName": "Skariah",
        "hall": 1501,
        "wing": "B",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "Hi name is Noel Skariah and I am interesting in music, dance, and helping others. I am interested in math and science and hope to become a doctor one day.",
        "mathcore": "MI I/II, MI II, MI III",
        "moreMath": "None",
        "cs": "None",
        "biology": "None",
        "chemistry": "SI Chemistry",
        "physics": "SI Physics",
        "language": "Spanish II",
        "otherScience": "MSI",
        "id": 125307,
        "graduationYear": 2025
    }
]

transform(d)